require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StocksController, type: :controller do

  let(:stock) { create(:stock) }

  describe '#index' do
    it 'assigns all stocks as @stocks' do
      get :index

      expect(response.status).to eql(200)
      expect(assigns(:stocks)).to eq([stock])
    end
  end

  describe '#show' do
    it 'assigns the requested stock as @stock' do
      get :show, {:id => stock.id}

      expect(response.status).to eql(200)
      expect(assigns(:stock)).to eq(stock)
    end
  end

  describe '#new' do
    it 'assigns a new stock as @stock' do
      get :new

      expect(response.status).to eql(200)
      expect(assigns(:stock)).to be_a_new(Stock)
    end
  end

  describe '#edit' do
    it 'assigns the requested stock as @stock' do
      get :edit, {:id => stock.id}

      expect(response.status).to eql(200)
      expect(assigns(:stock)).to eq(stock)
    end
  end

  describe '#create' do
    context 'with valid params' do
      it 'creates a new Stock' do
        expect {
          post :create, {:stock => build(:stock).as_json}
        }.to change(Stock, :count).by(1)
      end

      it 'assigns a newly created stock as @stock' do
        post :create, {:stock => build(:stock).as_json}

        expect(response.status).to eql(302)
        expect(assigns(:stock)).to be_a(Stock)
        expect(assigns(:stock)).to be_persisted
      end

      it 'redirects to the created stock' do
        post :create, {:stock => build(:stock).as_json}

        expect(response.status).to eql(302)
        expect(response).to redirect_to(Stock.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved stock as @stock' do
        new_stock = build(:stock)
        new_stock.quantity = nil

        expect(response.status).to eql(200)
        post :create, {:stock => new_stock.as_json}
        expect(assigns(:stock)).to be_a_new(Stock)
      end

      it "re-renders the 'new' template" do
        new_stock = build(:stock)
        new_stock.quantity = nil

        post :create, {:stock => new_stock.as_json}

        expect(response.status).to eql(200)
        expect(response).to render_template('new')
      end
    end
  end

  describe '#update' do
    context 'with valid params' do

      it 'updates the requested stock' do
        stock.quantity = 63

        put :update, {:id => stock.id, :stock => stock.as_json}

        expect(response.status).to eql(302)
        expect(stock.reload.quantity).to eql(63)
        expect(assigns(:stock)).to eq(stock)
        expect(response).to redirect_to(stock)
      end
    end

    context 'with invalid params' do
      it 'assigns the stock as @stock' do
        stock.quantity = nil

        put :update, {:id => stock.id, :stock => stock.as_json}

        expect(response.status).to eql(200)
        expect(assigns(:stock)).to eq(stock)
        expect(response).to render_template('edit')
      end
    end
  end

  describe '#destroy' do
    it 'destroys the requested stock' do
      delete :destroy, {:id => stock.id}

      expect(response.status).to eql(302)
      expect(Stock.first).to be_nil
      expect(response).to redirect_to(stocks_url)
    end
  end

end
